---
title: "Figure_3"
author: "izel"
date: "2025-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r warning=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(reshape2)
```

# Load datasets

```{r}
comix <- read.csv("/Users/df23614/Library/CloudStorage/OneDrive-UniversityofBristol/Shared Documents - grp-HPRU-RT/Avian influenza/Contact patterns/github_codes/AI_spillover_events/data/comix_processed_data.csv")
avcos <- read.csv("/Users/df23614/Library/CloudStorage/OneDrive-UniversityofBristol/Shared Documents - grp-HPRU-RT/Avian influenza/Contact patterns/github_codes/AI_spillover_events/data/contact_data(Avian_Contact_Study).csv")
```

# Regroup age of participants

```{r}
# regroup age of the participant
avcos <- avcos %>%
  mutate(part_age_merged = case_when(age >= 19 & age <= 29 ~ "19-29",
                   age >= 30 & age <= 39 ~ "30-39",
                   age >= 40 & age <= 49 ~ "40-49",
                   age >= 50 & age <= 59 ~ "50-59",
                   age >= 60 ~ "60+"))

comix <- comix %>% mutate(part_age_merged = case_when(
  part_age == "18-29" ~ "18-29",
  part_age == "30-39" ~ "30-39",
  part_age == "40-49" ~ "40-49",
  part_age == "50-59" ~ "50-59",
  part_age == "60-69" | part_age == "70-120" ~ "60+"
))

```

Filter data for desired age groups

```{r}
# CoMix
comix_18_29 <- comix %>% filter(part_age_merged == "18-29")
comix_30_39 <- comix %>% filter(part_age_merged == "30-39")
comix_40_49 <- comix %>% filter(part_age_merged == "40-49")
comix_50_59 <- comix %>% filter(part_age_merged== "50-59")
comix_60_plus <- comix %>% filter(part_age_merged == "60+")

# AvCos
avcos_18_29 <- avcos %>% filter(part_age_merged == "19-29")
avcos_30_39 <- avcos %>% filter(part_age_merged == "30-39")
avcos_40_49 <- avcos %>% filter(part_age_merged == "40-49")
avcos_50_59 <- avcos %>% filter(part_age_merged == "50-59")
avcos_60_plus <- avcos %>% filter(part_age_merged == "60+")
```

# Use the method of bootstrapping to calculate the mean with confidence intervals

For comix

```{r}
set.seed(123)

boot_means_all_comix <- replicate(2000, mean(sample(comix$cutoff_contact, replace = TRUE)))

boot_means_18_29_comix <- replicate(2000, mean(sample(comix_18_29$cutoff_contact, replace = TRUE)))


boot_means_30_39_comix <- replicate(2000, mean(sample(comix_30_39$cutoff_contact, replace = TRUE)))

boot_means_40_49_comix <- replicate(2000, mean(sample(comix_40_49$cutoff_contact, replace = TRUE)))


boot_means_50_59_comix <- replicate(2000, mean(sample(comix_50_59$cutoff_contact, replace = TRUE)))


boot_means_60_plus_comix <- replicate(2000, mean(sample(comix_60_plus$cutoff_contact, replace = TRUE)))

```


```{r}
mean_comix <- c(round(mean(boot_means_all_comix), 1),
                round(mean(boot_means_18_29_comix), 1),
                round(mean(boot_means_30_39_comix), 1),
                round(mean(boot_means_40_49_comix), 1),
                round(mean(boot_means_50_59_comix), 1),
                round(mean(boot_means_60_plus_comix), 1)
                )

lower_ci_comix <- c(quantile(boot_means_all_comix, probs = 0.025),
                    quantile(boot_means_18_29_comix, probs = 0.025),
                    quantile(boot_means_30_39_comix, probs = 0.025),
                    quantile(boot_means_40_49_comix, probs = 0.025),
                    quantile(boot_means_50_59_comix, probs = 0.025),
                    quantile(boot_means_60_plus_comix, probs = 0.025)
                    )

upper_ci_comix <- c(quantile(boot_means_all_comix, probs = 0.975),
                    quantile(boot_means_18_29_comix, probs = 0.975),
                    quantile(boot_means_30_39_comix, probs = 0.975),
                    quantile(boot_means_40_49_comix, probs = 0.975),
                    quantile(boot_means_50_59_comix, probs = 0.975),
                    quantile(boot_means_60_plus_comix, probs = 0.975)
                    )

```

For avcos

```{r}
set.seed(123)

boot_means_all_avcos <- replicate(2000, mean(sample(avcos$contact_count, replace = TRUE)))

boot_means_18_29_avcos <- replicate(2000, mean(sample(avcos_18_29$contact_count, replace = TRUE)))


boot_means_30_39_avcos <- replicate(2000, mean(sample(avcos_30_39$contact_count, replace = TRUE)))

boot_means_40_49_avcos <- replicate(2000, mean(sample(avcos_40_49$contact_count, replace = TRUE)))


boot_means_50_59_avcos <- replicate(2000, mean(sample(avcos_50_59$contact_count, replace = TRUE)))


boot_means_60_plus_avcos <- replicate(2000, mean(sample(avcos_60_plus$contact_count, replace = TRUE)))
```

```{r}
mean_avcos <- c(round(mean(boot_means_all_avcos), 1),
                round(mean(boot_means_18_29_avcos), 1),
                round(mean(boot_means_30_39_avcos), 1),
                round(mean(boot_means_40_49_avcos), 1),
                round(mean(boot_means_50_59_avcos), 1),
                round(mean(boot_means_60_plus_avcos), 1)
                )

lower_ci_avcos <- c(quantile(boot_means_all_avcos, probs = 0.025),
                    quantile(boot_means_18_29_avcos, probs = 0.025),
                    quantile(boot_means_30_39_avcos, probs = 0.025),
                    quantile(boot_means_40_49_avcos, probs = 0.025),
                    quantile(boot_means_50_59_avcos, probs = 0.025),
                    quantile(boot_means_60_plus_avcos, probs = 0.025)
                    )

upper_ci_avcos <- c(quantile(boot_means_all_avcos, probs = 0.975),
                    quantile(boot_means_18_29_avcos, probs = 0.975),
                    quantile(boot_means_30_39_avcos, probs = 0.975),
                    quantile(boot_means_40_49_avcos, probs = 0.975),
                    quantile(boot_means_50_59_avcos, probs = 0.975),
                    quantile(boot_means_60_plus_avcos, probs = 0.975)
                    )

```

# Calculate the 25% and 75% quantiles of the data

Avcos

```{r}
lower_qnt_avcos <- c(quantile(avcos$contact_count, 0.25),
                     quantile(avcos_18_29$contact_count, 0.25),
                     quantile(avcos_30_39$contact_count, 0.25),
                     quantile(avcos_40_49$contact_count, 0.25),
                     quantile(avcos_50_59$contact_count, 0.25),
                     quantile(avcos_60_plus$contact_count, 0.25))

upper_qnt_avcos <- c(quantile(avcos$contact_count, 0.75),
                     quantile(avcos_18_29$contact_count, 0.75),
                     quantile(avcos_30_39$contact_count, 0.75),
                     quantile(avcos_40_49$contact_count, 0.75),
                     quantile(avcos_50_59$contact_count, 0.75),
                     quantile(avcos_60_plus$contact_count, 0.75))
```

CoMix

```{r}
lower_qnt_comix <- c(quantile(comix$cutoff_contact, 0.25),
                     quantile(comix_18_29$cutoff_contact, 0.25),
                     quantile(comix_30_39$cutoff_contact, 0.25),
                     quantile(comix_40_49$cutoff_contact, 0.25),
                     quantile(comix_50_59$cutoff_contact, 0.25),
                     quantile(comix_60_plus$cutoff_contact, 0.25))

upper_qnt_comix <- c(quantile(comix$cutoff_contact, 0.75),
                     quantile(comix_18_29$cutoff_contact, 0.75),
                     quantile(comix_30_39$cutoff_contact, 0.75),
                     quantile(comix_40_49$cutoff_contact, 0.75),
                     quantile(comix_50_59$cutoff_contact, 0.75),
                     quantile(comix_60_plus$cutoff_contact, 0.75))
```

# Combine the data and plot the results

```{r}
forest_data <- data.frame("category" = c("overall", "18-29", "30-39", "40-49", "50-59", "60+", "overall", "18-29", "30-39", "40-49", "50-59", "60+"),
                          "lower_qnt" = c(lower_qnt_avcos,
                                         lower_qnt_comix),
                          "upper_qnt" = c(upper_qnt_avcos,
                                         upper_qnt_comix),
                          "mean_contact" = c(mean_avcos, mean_comix),
                          "lower_ci" = c(lower_ci_avcos,
                                         lower_ci_comix),
                          "upper_ci" = c(upper_ci_avcos,
                                         upper_ci_comix),
                          "survey" = rep(c("AvCos", "CoMix"), each = 6))

# Number of participants in each age group

num_parts <- data.frame("category" = c("overall", "18-29", "30-39", "40-49", "50-59", "60+", "overall", "18-29", "30-39", "40-49", "50-59", "60+"),
                        "number_participants" = c(197, 17, 42, 34, 56, 48, 2388, 402, 440, 349, 431, 766),
                        "survey" = rep(c("AvCos", "CoMix"), each = 6))


fig_3 <- ggplot(forest_data, aes(y = category)) +
  
  geom_point(aes(x = mean_contact, group = survey, shape = survey), size = 3, position = position_dodge(width = 0.5)) +  # Mean values
  geom_errorbar(aes(xmin = lower_qnt, xmax = upper_qnt, group = survey, colour = "IQR"), width = 0.5, position = position_dodge(width = 0.5)) +  # quantile bars
  geom_errorbar(aes(xmin = lower_ci, xmax = upper_ci, group = survey),
              width = 0.2, position = position_dodge(width = 0.5)) +  # CI bars
  
  geom_text(data = num_parts,                                  # number of participants as a text
          aes(x = 10.5,  
              y = category,
              label = paste0("N = ", number_participants), group = survey),
          position = position_dodge(width = 0.5),
          hjust = 0,
          size = 3.5,
          show.legend = FALSE) +
  
  labs(x = "Number of contacts", y = "Age group", shape = "Survey", colour = "Colour") +
  scale_colour_manual(values = c("IQR" = "grey"
                                 )) +
  scale_shape_manual(values = c("CoMix" = "triangle", "AvCos" = "circle")) +
  scale_x_continuous(breaks = seq(0, 10, 1)) +
  expand_limits(x = 10 + 2) +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "white", colour = NA))

```

```{r}
ggsave("/Users/df23614/Library/CloudStorage/OneDrive-UniversityofBristol/Shared Documents - grp-HPRU-RT/Avian influenza/Contact patterns/Figure_formatted/Fig_3.tiff", fig_3, dpi = 300, width = 6, height = 4.7, units = "in", device = "tiff", compression = "lzw")
```
