---
title: "contact_matrix_nb_dist"
author: "izel"
date: "2025-04-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(patchwork)
library(fitdistrplus)
library(rlang)
library(ggpubr)
```

# Data (contact data from the Avian Contact Study)

```{r}
cont_cleaned <- read.csv("/Users/df23614/Library/CloudStorage/OneDrive-UniversityofBristol/Shared Documents - grp-HPRU-RT/Avian influenza/Contact patterns/github_codes/AI_spillover_events/cont_cleaned.csv")

# extract columns that we will use
data <- cont_cleaned[, c(2, 563, 409, 415, 421, 427, 433, 439, 445, 451, 457, 463, 469, 475, 481, 487, 493, 499, 505, 511, 517, 523, 569, 572)]
```

# Negative binomial distribution

```{r}
nb_fit <- fitdist(data$contact_count, "nbinom")

cnt_dat <- data %>%
  group_by(contact_count) %>%
  tally() %>%
  ungroup()

cnt_dat <- cnt_dat %>%
  complete(contact_count = seq(1, 20, 1), fill = list(n = 0))

cnt_dat <- cnt_dat %>%
  mutate(n_fit = dnbinom(contact_count, size = nb_fit$estimate[1], mu = nb_fit$estimate[2]))

cnt_dat$n_fit <- cnt_dat$n_fit * sum(cnt_dat$n)

```

Get confidence intervals around the fit

```{r}
# assume size follows gamma dist and mu follows normal dist

# parameters of gamma: shape and scale. mean = shape*scale, variance = shape * scale^2

scale_gamma <- nb_fit$sd[1]^2/nb_fit$estimate[1]
shape_gamma <- nb_fit$estimate[1]/scale_gamma

size_param <- rgamma(1000, scale = scale_gamma, shape = shape_gamma)

mu_param <- rnorm(1000, mean = nb_fit$estimate[2], sd = nb_fit$sd[2])

df_params <- data.frame(sim = seq(1,1000,1),
                        size = size_param,
                        mu = mu_param)


```

```{r}
new_data <- cnt_dat[, c(1, 2)]

for (i in 1:length(df_params$sim)) {
  
  col_name <- paste0("n_fit_", i) 
  
  new_data <- new_data %>%
    mutate(!!sym(col_name) := dnbinom(contact_count, size = df_params$size[i], mu = df_params$mu[i]) * sum(new_data$n)) # !!sym is used in mutate to update the column name accordingly
  
}
```

Plotting the results

```{r}
# First convert into long format

n_fit_cols <- grep("^n_fit_", names(new_data), value = TRUE) # extract the name of the columns that start with n_fit_

new_data_long <- melt(new_data, id.vars = "contact_count",
                      measure.vars = n_fit_cols,
                      variable.name = "n_fit")

dist_all_age <- ggplot() +
  geom_bar(data = cnt_dat, aes(x = contact_count, y = n), stat = "identity", fill = "skyblue", colour = "navy") +
  geom_line(data = new_data_long, aes(x = contact_count, y = value, group = n_fit), alpha = 0.06, colour = "pink") +
  geom_line(data = cnt_dat, aes(x = contact_count, y = n_fit), colour = "red") +
  geom_point(data = cnt_dat, aes(x = contact_count, y = n_fit), colour = "red") +
  labs(x = "Number of contacts", y = "Frequency") +
  scale_y_continuous(breaks = seq(0, max(cnt_dat$n), 5)) +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "white", colour = NA))
```

```{r}
ggsave("/Users/df23614/Library/CloudStorage/OneDrive-UniversityofBristol/Shared Documents - grp-HPRU-RT/Avian influenza/Contact patterns/Figure_formatted/Fig_2a.tiff", dist_all_age, dpi = 300, width = 6, height = 5, units = "in", device = "tiff", compression = "lzw")
```

# Contact matrices

```{r}
# regroup age of the participant
data <- data %>%
  mutate(age_group_cm = case_when(age >= 19 & age <= 29 ~ "19-29",
                                  age >= 30 & age <= 39 ~ "30-39",
                                  age >= 40 & age <= 49 ~ "40-49",
                                  age >= 50 & age <= 59 ~ "50-59",
                                  age >= 60 & age <= 69 ~ "60-69",
                                  age >= 70 ~ "70+"))

cont_cleaned <- cont_cleaned %>%
  mutate(age_group_cm = case_when(age >= 19 & age <= 29 ~ "19-29",
                                  age >= 30 & age <= 39 ~ "30-39",
                                  age >= 40 & age <= 49 ~ "40-49",
                                  age >= 50 & age <= 59 ~ "50-59",
                                  age >= 60 & age <= 69 ~ "60-69",
                                  age >= 70 ~ "70+"))

# regroup age of the contact
regroup_age <- function(age_contact) {
  case_when(
    age_contact %in% c("Under 1", "1 - 4") ~ "0-4",
    age_contact == "5 - 9" ~ "5-9",
    age_contact == "10 - 14" ~ "10-14",
    age_contact == "15 - 19" ~ "15-19",
    age_contact %in% c("20 - 24", "25 - 29") ~ "20-29",
    age_contact %in% c("30 - 34", "35 - 39") ~ "30-39",
    age_contact %in% c("40 - 44", "45 - 49") ~ "40-49",
    age_contact %in% c("50 - 54", "55 - 59") ~ "50-59",
    age_contact %in% c("60 - 64", "65 - 70") ~ "60-69",
    age_contact == "70+" ~ "70+",
    is.na(age_contact) ~ NA_character_,
    TRUE ~ "I don't know"
  )
}

data <- data %>%
  mutate(across(starts_with("sec3_q2_age"), regroup_age))

cont_cleaned <- cont_cleaned %>%
  mutate(across(starts_with("sec3_q2_age"), regroup_age))
```

# contact matrices

# Average number of contact per person across all contacts

```{r}
age_long <- melt(data, id.vars = "age_group_cm",
                 measure.vars = c("sec3_q2_age1.factor", "sec3_q2_age2.factor",
                                  "sec3_q2_age3.factor", "sec3_q2_age4.factor",
                                  "sec3_q2_age5.factor", "sec3_q2_age6.factor",
                                  "sec3_q2_age7.factor", "sec3_q2_age8.factor",
                                  "sec3_q2_age9.factor", "sec3_q2_age10.factor",
                                  "sec3_q2_age11.factor", "sec3_q2_age12.factor",
                                  "sec3_q2_age13.factor", "sec3_q2_age14.factor",
                                  "sec3_q2_age15.factor", "sec3_q2_age16.factor",
                                  "sec3_q2_age17.factor", "sec3_q2_age18.factor",
                                  "sec3_q2_age19.factor", "sec3_q2_age20.factor"),
                 variable.name = "age",
                 value.name = "value")

value_age_long <- age_long %>%
  group_by(age_group_cm, value) %>%
  tally() %>%
  ungroup()

# ignore NA
value_age_long <- na.omit(value_age_long)

value_age_long <- value_age_long %>%
  complete(age_group_cm, value = data$sec3_q2_age1.factor, fill = list(n = 0))

# ignore NA
value_age_long <- na.omit(value_age_long)

# average number of contact per person 
value_age_long <- value_age_long %>%
  mutate(mean_n = case_when(
    age_group_cm == "19-29" ~ n / table(data$age_group_cm)[[1]],
    age_group_cm == "30-39" ~ n / table(data$age_group_cm)[[2]],
    age_group_cm == "40-49" ~ n / table(data$age_group_cm)[[3]],
    age_group_cm == "50-59" ~ n / table(data$age_group_cm)[[4]],
    age_group_cm == "60-69" ~ n / table(data$age_group_cm)[[5]],
    age_group_cm == "70+" ~ n / table(data$age_group_cm)[[6]]
  ))

value_age_long$value <- factor(value_age_long$value, levels = c("0-4", "5-9",
                                                                "10-14", "15-19",
                                                                "20-29", "30-39",
                                                                "40-49", "50-54",
                                                                "50-59", "60-69",
                                                                "70+", "I don't know"))


value_age_long$age_group_cm <- factor(value_age_long$age_group_cm, levels = c("19-29", "30-39", "40-49", "50-59", "60-69", "70+"))

## contact matrix                              
matrix_n <- ggplot(value_age_long, aes(x = age_group_cm, y = value, fill = mean_n)) +
  geom_tile() +
  labs(x = "Age group of the participant",
       y = "Age group of the contact",
       title = "All contacts",
       fill = "Mean contacts
(per person per day)") +
  scale_fill_gradient(low = "white", high = "red") +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(
    legend.title = element_text(size = 8),
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10),
    title = element_text(size = 8)
  ) +
  theme(plot.background = element_rect(fill = "white", colour = NA))

```

# Average number of contact per person stratified by family contacts

```{r}

who_long_age <- melt(cont_cleaned, id.vars = "age_group_cm",
                     measure.vars = c("sec3_q2_who1.factor", "sec3_q2_who2.factor",
                                      "sec3_q2_who3.factor", "sec3_q2_who4.factor",
                                      "sec3_q2_who5.factor", "sec3_q2_who6.factor",
                                      "sec3_q2_who7.factor", "sec3_q2_who8.factor",
                                      "sec3_q2_who9.factor", "sec3_q2_who10.factor",
                                      "sec3_q2_who11.factor", "sec3_q2_who12.factor",
                                      "sec3_q2_who13.factor", "sec3_q2_who14.factor",
                                      "sec3_q2_who15.factor", "sec3_q2_who16.factor",
                                      "sec3_q2_who17.factor", "sec3_q2_who18.factor",
                                      "sec3_q2_who19.factor", "sec3_q2_who20.factor"),
                     variable.name = "who",
                     value.name = "value_who")

who_age_long <- bind_cols(age_long, who_long_age)

who_age_long$age_group <- who_age_long$age_group_cm...1
who_age_long <- who_age_long[, -c(1, 4)]

# filter who_age_long to include only family
who_age_long <- who_age_long %>%
  filter(value_who == "Family")


value_who_age_long <- who_age_long %>%
  group_by(age_group, value) %>%
  tally() %>%
  ungroup()

value_who_age_long <- value_who_age_long %>%
  complete(age_group, value = cont_cleaned$sec3_q2_age1.factor, fill = list(n = 0))

# ignore NA
value_who_age_long <- na.omit(value_who_age_long)

# average number of contact per person 
value_who_age_long <- value_who_age_long %>%
  mutate(mean_n = case_when(
    age_group == "19-29" ~ n / table(data$age_group_cm)[[1]],
    age_group == "30-39" ~ n / table(data$age_group_cm)[[2]],
    age_group == "40-49" ~ n / table(data$age_group_cm)[[3]],
    age_group == "50-59" ~ n / table(data$age_group_cm)[[4]],
    age_group == "60-69" ~ n / table(data$age_group_cm)[[5]],
    age_group == "70+" ~ n / table(data$age_group_cm)[[6]]
  ))

value_who_age_long$value <- factor(value_who_age_long$value, levels = c("0-4", "5-9",
                                                                "10-14", "15-19",
                                                                "20-29", "30-39",
                                                                "40-49", "50-54",
                                                                "50-59", "60-69",
                                                                "70+", "I don't know"))


value_who_age_long$age_group <- factor(value_who_age_long$age_group, levels = c("19-29", "30-39", "40-49", "50-59", "60-69", "70+"))

## contact matrix at home                              
family_matrix_n <- ggplot(value_who_age_long, aes(x = age_group, y = value, fill = mean_n)) +
  geom_tile() +
  labs(x = "Age group of the participant",
       y = "",
       title = "Family contacts",
       fill = "Mean contacts
(per person per day)") +
  scale_fill_gradient(low = "white", high = "red") +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(
    legend.title = element_text(size = 8),
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    axis.title.x = element_text(size = 10),
    title = element_text(size = 8)
  ) +
  theme(plot.background = element_rect(fill = "white", colour = NA))

```

```{r}
fig_2b <- matrix_n + family_matrix_n
fig_2b <- fig_2b + coord_fixed(ratio = 1)
```

```{r}
bottom_row <- ggarrange(matrix_n, family_matrix_n,
                        labels = c("B", "C"),
                        ncol = 2,
                        widths = c(1, 1))

fig_2 <- ggarrange(dist_all_age, bottom_row,
                   labels = "A",
                   ncol = 1,
                   heights = c(1, 1))
```

```{r}
ggsave("/Users/df23614/Library/CloudStorage/OneDrive-UniversityofBristol/Shared Documents - grp-HPRU-RT/Avian influenza/Contact patterns/Figure_formatted/Fig_2.tiff", fig_2, dpi = 300, width = 7.5, height = 6, units = "in", device = "tiff", compression = "lzw")
```

```{r}
## contact matrix at home                              
family_matrix_n <- ggplot(value_who_age_long, aes(x = age_group, y = value, fill = mean_n)) +
  geom_tile() +
  labs(x = "Age of participant",
       y = "Age of contact",
       title = "Family contacts",
       fill = "Contacts") +
  scale_fill_gradient(low = "white", high = "red") +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 12),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    title = element_text(size = 12)
  )

```