---
title: "fig4(ct)"
author: "izel"
date: "2025-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
# R: 0

trial_04_04_0_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_0_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_0_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_0_500_0 <- combination_function(trial_04_04_0_500_0_20_44, trial_04_04_0_500_0_45_59, trial_04_04_0_500_0_60_plus)

saveRDS(res_04_04_0_500_0, file = file.path(folder_path, "res_04_04_0_500_0.rds"))

# R: 0.1

trial_04_04_01_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.1, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_01_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.1, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_01_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.1, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_01_500_0 <- combination_function(trial_04_04_01_500_0_20_44, trial_04_04_01_500_0_45_59, trial_04_04_01_500_0_60_plus)

saveRDS(res_04_04_01_500_0, file = file.path(folder_path, "res_04_04_01_500_0.rds"))

# R: 0.2

trial_04_04_02_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.2, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_02_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.2, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_02_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.2, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_02_500_0 <- combination_function(trial_04_04_02_500_0_20_44, trial_04_04_02_500_0_45_59, trial_04_04_02_500_0_60_plus)

saveRDS(res_04_04_02_500_0, file = file.path(folder_path, "res_04_04_02_500_0.rds"))

# R: 0.3

trial_04_04_03_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.3, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_03_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.3, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_03_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.3, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_03_500_0 <- combination_function(trial_04_04_03_500_0_20_44, trial_04_04_03_500_0_45_59, trial_04_04_03_500_0_60_plus)

saveRDS(res_04_04_03_500_0, file = file.path(folder_path, "res_04_04_03_500_0.rds"))

# R: 0.4

trial_04_04_04_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.4, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_04_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.4, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_04_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.4, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_04_500_0 <- combination_function(trial_04_04_04_500_0_20_44, trial_04_04_04_500_0_45_59, trial_04_04_04_500_0_60_plus)

saveRDS(res_04_04_04_500_0, file = file.path(folder_path, "res_04_04_04_500_0.rds"))

# R: 0.5

trial_04_04_05_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.5, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_05_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.5, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_05_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.5, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_05_500_0 <- combination_function(trial_04_04_05_500_0_20_44, trial_04_04_05_500_0_45_59, trial_04_04_05_500_0_60_plus)

saveRDS(res_04_04_05_500_0, file = file.path(folder_path, "res_04_04_05_500_0.rds"))

# R: 0.6

trial_04_04_06_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.6, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_06_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.6, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_06_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.6, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_06_500_0 <- combination_function(trial_04_04_06_500_0_20_44, trial_04_04_06_500_0_45_59, trial_04_04_06_500_0_60_plus)

saveRDS(res_04_04_06_500_0, file = file.path(folder_path, "res_04_04_06_500_0.rds"))

# R: 0.7

trial_04_04_07_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.7, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_07_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.7, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_07_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.7, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_07_500_0 <- combination_function(trial_04_04_07_500_0_20_44, trial_04_04_07_500_0_45_59, trial_04_04_07_500_0_60_plus)

saveRDS(res_04_04_07_500_0, file = file.path(folder_path, "res_04_04_07_500_0.rds"))

# R: 0.8

trial_04_04_08_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.8, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_08_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.8, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_08_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.8, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_08_500_0 <- combination_function(trial_04_04_08_500_0_20_44, trial_04_04_08_500_0_45_59, trial_04_04_08_500_0_60_plus)

saveRDS(res_04_04_08_500_0, file = file.path(folder_path, "res_04_04_08_500_0.rds"))

# R: 0.9

trial_04_04_09_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.9, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_09_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.9, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_09_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 0.9, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_09_500_0 <- combination_function(trial_04_04_09_500_0_20_44, trial_04_04_09_500_0_45_59, trial_04_04_09_500_0_60_plus)

saveRDS(res_04_04_09_500_0, file = file.path(folder_path, "res_04_04_09_500_0.rds"))

# R: 1

trial_04_04_1_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 1, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_1_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 1, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_1_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 1, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_1_500_0 <- combination_function(trial_04_04_1_500_0_20_44, trial_04_04_1_500_0_45_59, trial_04_04_1_500_0_60_plus)

saveRDS(res_04_04_1_500_0, file = file.path(folder_path, "res_04_04_1_500_0.rds"))

# R: 1.1

trial_04_04_11_500_0_20_44 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 1.1, time_isolation = 500, index_age_group = "20-44", p_isolate = 0)
trial_04_04_11_500_0_45_59 <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 1.1, time_isolation = 500, index_age_group = "45-59", p_isolate = 0)
trial_04_04_11_500_0_60_plus <- function_age(p_asym = 0.4, p_trace = 0.4, R_0 = 1.1, time_isolation = 500, index_age_group = "60+", p_isolate = 0)

res_04_04_11_500_0 <- combination_function(trial_04_04_11_500_0_20_44, trial_04_04_11_500_0_45_59, trial_04_04_11_500_0_60_plus)

saveRDS(res_04_04_11_500_0, file = file.path(folder_path, "res_04_04_11_500_0.rds"))
```
